# Generated by Django 5.0.1 on 2024-02-07 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_category_product_image_product_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='sybcategory',
            new_name='sub_category',
        ),
    ]
